export const stepOneFieldsArray = [
  // {
  //   section: "deed",
  //   name: "deedNo",
  //   label: "Deed No *",
  //   placeholder: "eg., D-2024-5245",
  //   rules: { required: "Deed No is required" },
  //   helperText: "Unique legal number assigned to this deed",
  // },
  {
    section: "deed",
    name: "dateOfRegistration",
    label: "Date of registration *",
    type: "date",
    // rules: { required: "Date of registration is required" },
    InputLabelProps: { shrink: true },
  },
  {
    section: "deed",
    name: "nameOfSeller",
    label: "Name of the Seller *",
    placeholder: "Enter Seller name",
    rules: { required: "Seller name is required" },
  },
  {
    section: "deed",
    name: "nameOfPurchaser",
    label: "Name of the Purchaser *",
    placeholder: "Enter Purchaser name",
    rules: { required: "Purchaser name is required" },
  },
  {
    section: "deed",
    name: "mutatedOrLeased",
    label: "Mutated / Leased *",
    placeholder: "Enter Mutated / Leased in the name of CO",
    rules: { required: "Purchaser name is required" },
  },
  {
    section: "deed",
    name: "nameOfMouza",
    label: "Mouza Name",
    placeholder: "Enter mouza",
    rules: { required: "Required" },
  },
  {
    section: "deed",
    name: "khatianNo",
    label: "Khatian No",
    placeholder: "Enter khatian",
    rules: { required: "Required" },
  },
  {
    section: "deed",
    name: "mutatedKhatianNo",
    label: "Mutated Khaitan Number",
    type: "number",
    placeholder: "0.00",
  },

  // ================= Area & Mutation =================
];

export const stepTwoFieldsArray = [
  {
    section: "plot",
    name: "plotNo",
    label: "Plot No",
    variant: "filled",
    placeholder: "Enter plot",
    rules: { required: "Required" },
  },
  {
    section: "plot",
    name: "locationOfPurchasedLand",
    label: "Location of Purchased Land",
    variant: "filled",
    placeholder: "e.g., North-West corner adjacent to NH-34",
    rules: { required: "Required" },
  },
  {
    section: "calculation",
    name: "totalAreaOfplotNo",
    label: "Total Area of Plot",
    type: "number",
    placeholder: "0.00",
    rules: { required: "Required" },
  },
  {
    section: "calculation",
    name: "totalPurchasedArea",
    label: "Purchased Area as per Deed",
    type: "number",
    placeholder: "0.00",
    rules: { required: "Required" },
  },
  {
    section: "calculation",
    name: "purchasedLand",
    label: "Purchased Land ( D )",
    type: "number",
    placeholder: "0.00",
    rules: { required: "Required" },
  },
  {
    section: "calculation",
    name: "actualLandPurchasedLeased",
    label: "Actual Land Purchased & Leased  ( E )",
    type: "number",
    placeholder: "0.00",
    rules: { required: "Required" },
  },
  {
    section: "calculation",
    name: "totalMutatedArea",
    label: "Total Mutated Area ( B )",
    type: "number", variant: "filled",
    placeholder: "0.00", disabled: true,
    rules: { required: "Required" },
    helperText: "Auto-calculated: D + E",
  },
  {
    section: "calculation",
    name: "nonMutatedArea",
    label: "Non-Mutated Area ( C ) ",
    type: "number", variant: "filled",
    placeholder: "0.00",
    disabled: true,
    helperText: "Auto-calculated: Purchased - B",
    rules: { required: "Required" },
  },
  {
    section: "calculation",
    name: "excessMutated",
    label: "Excess Mutated / Deed Not Received ( A )",
    type: "number", variant: "filled",
    placeholder: "0.00", disabled: true,
    helperText: "Auto-calculated: B + C",
  },  
];